import Header from '@/components/layout/header/header';
import { ClerkProvider } from '@clerk/nextjs';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './../globals.css';
import { Toaster } from 'react-hot-toast';
import Footer from '@/components/layout/footer/footer';

const raleway = localFont({
  src: '../fonts/Raleway.woff2',
  variable: '--font-raleway',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${raleway.variable} antialiased`}>
          <Header />
          {children}
          <Footer />
          <Toaster
            position="bottom-right"
            toastOptions={{
              style: {
                background: '#000000',
                color: '#ffffff',
              },
            }}
          />
        </body>
      </html>
    </ClerkProvider>
  );
}
